Repository volcano-sh/apis, pull requests merged in 2021-11, with the labels that each got.

#54 add dependsOn for task
  README.md
  pkg/apis/batch/v1alpha1/job.go
  pkg/apis/batch/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/bus/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/nodeinfo/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/scheduling/v1beta1/zz_generated.deepcopy.go
Labels: size/M, lgtm, approved

#55 Optimize the structure
  pkg/apis/batch/v1alpha1/job.go
  pkg/apis/batch/v1alpha1/zz_generated.deepcopy.go
Labels: size/XS, lgtm, approved

#56 add annotation for fields
  pkg/apis/batch/v1alpha1/job.go
Labels: size/XS, lgtm, approved

#58 cleanup DeleteConfigmap
  pkg/apis/helpers/helpers.go
Labels: size/S, lgtm, approved

#59 add annotation key TopologyDecisionAnnotation
  pkg/apis/scheduling/v1beta1/labels.go
Labels: size/XS, lgtm, approved
