Repository volcano-sh/apis, pull requests merged in 2022-07, with the labels that each got.

#77 Show more information when using kubectl to get pg v1beta1 version
  pkg/apis/scheduling/v1beta1/types.go
Labels: size/S, lgtm, approved

#78 update jobflow and jobtemplate
  pkg/apis/flow/v1alpha1/actions.go
  pkg/apis/flow/v1alpha1/events.go
  pkg/apis/flow/v1alpha1/register.go
  pkg/apis/helpers/helpers.go
Labels: size/S, lgtm, approved

#80 add related xx_deepcopy.go for queue.spec.affinity
  pkg/apis/scheduling/v1beta1/zz_generated.conversion.go
  pkg/apis/scheduling/v1beta1/zz_generated.deepcopy.go
  pkg/apis/scheduling/zz_generated.deepcopy.go
Labels: lgtm, approved, size/L

#82 update PreemptStableTime to CooldownTime
  pkg/apis/scheduling/v1beta1/labels.go
Labels: size/XS, lgtm, approved

#83 add volcano group min resources annotation key
  pkg/apis/scheduling/v1beta1/labels.go
Labels: size/XS, lgtm, approved
