Repository volcano-sh/apis, pull requests merged in 2022-04, with the labels that each got.

#69 add additionalPrinterColumns
  pkg/apis/batch/v1alpha1/job.go
  pkg/apis/scheduling/types.go
Labels: size/XS, lgtm, approved

#68 add stable preempt label
  pkg/apis/scheduling/v1beta1/labels.go
Labels: size/XS, lgtm, approved

#66 feat(apis): add completed state to podgroup&queue
  pkg/apis/scheduling/types.go
  pkg/apis/scheduling/v1beta1/types.go
  pkg/apis/scheduling/v1beta1/zz_generated.conversion.go
Labels: size/S, lgtm, approved

#62 feature: add memory numa info
  pkg/apis/nodeinfo/v1alpha1/numatopo_types.go
Labels: size/M, lgtm, approved

#71 Revert "feature: add memory numa info"
  pkg/apis/nodeinfo/v1alpha1/numatopo_types.go
Labels: size/M, lgtm, approved
