Repository volcano-sh/apis, pull requests merged in 2024-12, with the labels that each got.

#143 Add RestartPod action for pod reschedule
  pkg/apis/bus/v1alpha1/actions.go
Labels: size/XS, lgtm, approved

#146 chore: adapt volcano apis to k8s 1.31.3
  go.mod
  go.sum
  hack/generate-groups.sh
  hack/generate-internal-groups.sh
Labels: size/M, lgtm, approved

#144 Network topology API definition
  pkg/apis/batch/v1alpha1/job.go
  pkg/apis/batch/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/scheduling/types.go
  pkg/apis/scheduling/v1beta1/types.go
  pkg/apis/scheduling/v1beta1/zz_generated.conversion.go
  pkg/apis/scheduling/v1beta1/zz_generated.deepcopy.go
  pkg/apis/scheduling/zz_generated.deepcopy.go
  pkg/apis/topology/v1alpha1/doc.go
  pkg/apis/topology/v1alpha1/hypernode_types.go
  pkg/apis/topology/v1alpha1/register.go
  pkg/apis/topology/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/topology/v1alpha1/zz_generated.defaults.go
  pkg/client/applyconfiguration/batch/v1alpha1/jobspec.go
  pkg/client/applyconfiguration/batch/v1alpha1/networktopologyspec.go
  pkg/client/applyconfiguration/scheduling/v1beta1/networktopologyspec.go
  pkg/client/applyconfiguration/scheduling/v1beta1/podgroupspec.go
  pkg/client/applyconfiguration/topology/v1alpha1/exactmatch.go
  pkg/client/applyconfiguration/topology/v1alpha1/hypernode.go
  pkg/client/applyconfiguration/topology/v1alpha1/hypernodespec.go
  pkg/client/applyconfiguration/topology/v1alpha1/hypernodestatus.go
  pkg/client/applyconfiguration/topology/v1alpha1/memberselector.go
  pkg/client/applyconfiguration/topology/v1alpha1/memberspec.go
  pkg/client/applyconfiguration/topology/v1alpha1/regexmatch.go
  pkg/client/applyconfiguration/utils.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/topology/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/topology/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/topology/v1alpha1/fake/fake_hypernode.go
  pkg/client/clientset/versioned/typed/topology/v1alpha1/fake/fake_topology_client.go
  pkg/client/clientset/versioned/typed/topology/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/topology/v1alpha1/hypernode.go
  pkg/client/clientset/versioned/typed/topology/v1alpha1/topology_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/topology/interface.go
  pkg/client/informers/externalversions/topology/v1alpha1/hypernode.go
  pkg/client/informers/externalversions/topology/v1alpha1/interface.go
  pkg/client/listers/topology/v1alpha1/expansion_generated.go
  pkg/client/listers/topology/v1alpha1/hypernode.go
Labels: lgtm, approved, size/XXL

#148 export MemberTypeHyperNode field
  pkg/apis/topology/v1alpha1/hypernode_types.go
Labels: size/XS, lgtm, approved
