Repository volcano-sh/apis, pull requests merged in 2025-09, with the labels that each got.

#193 Add constants for NetworkTopology related key
  pkg/apis/topology/v1alpha1/labels.go
Labels: size/S, lgtm, approved

#194 Fix Job applyconfiguration
  hack/update-codegen.sh
  pkg/client/applyconfiguration/batch/v1alpha1/taskspec.go
Labels: size/S, lgtm, approved

#184 [feature] add patch field and do codegen
  pkg/apis/flow/v1alpha1/jobflow_types.go
  pkg/apis/flow/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/flow/v1alpha1/flow.go
  pkg/client/applyconfiguration/flow/v1alpha1/patch.go
  pkg/client/applyconfiguration/utils.go
Labels: lgtm, approved, size/L

#186 Remove deprecated field in Queue.Spec, and generate auto convert func for Queue.Spec
  pkg/apis/scheduling/types.go
  pkg/apis/scheduling/v1beta1/conversion.go
  pkg/apis/scheduling/v1beta1/zz_generated.conversion.go
Labels: size/M, lgtm, approved

#192 apis: add CronJob resource
  pkg/apis/batch/v1alpha1/job.go
  pkg/apis/batch/v1alpha1/labels.go
  pkg/apis/batch/v1alpha1/register.go
  pkg/apis/batch/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/batch/v1alpha1/cronjob.go
  pkg/client/applyconfiguration/batch/v1alpha1/cronjobspec.go
  pkg/client/applyconfiguration/batch/v1alpha1/cronjobstatus.go
  pkg/client/applyconfiguration/batch/v1alpha1/jobtemplatespec.go
  pkg/client/applyconfiguration/utils.go
  pkg/client/clientset/versioned/typed/batch/v1alpha1/batch_client.go
  pkg/client/clientset/versioned/typed/batch/v1alpha1/cronjob.go
  pkg/client/clientset/versioned/typed/batch/v1alpha1/fake/fake_batch_client.go
  pkg/client/clientset/versioned/typed/batch/v1alpha1/fake/fake_cronjob.go
  pkg/client/clientset/versioned/typed/batch/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/batch/v1alpha1/cronjob.go
  pkg/client/informers/externalversions/batch/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/batch/v1alpha1/cronjob.go
  pkg/client/listers/batch/v1alpha1/expansion_generated.go
Labels: lgtm, approved, size/XXL
